# Generated by Django 5.1.7 on 2025-03-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
